apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
  - name: test-container
    image: psrv3/newconfigmapexample
    ports:
    - containerPort: 5001
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: my-flask-config
          key: NAME
