groups:
  - name: custom_rules
    rules:
      - record: node_memory_MemFree_percent
        expr: 100-(100 * node_memory_MemFree_bytes/node_memory_MemTotal_bytes)
  - name: example_new
    rules:
    - record: code:prometheus_http_requests_total:sum
      expr: sum by (code) (prometheus_http_requests_total)
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "The instance {{ $labels.instance }} has been down for more than 1 minute."
      - alert: HighCpuUtilization
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU utilization detected"
          description: "CPU utilization has been above 80% for more than 5 minutes."
