apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
    version: blue
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
